[package]
name = "frqstbite/fusion-plugin"
description = "Rediscover the joy of plugins."
version = "1.1.3"
license = "MIT"
authors = ["frqstbite <frqstbite1001@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]